# Generated by Django 3.2.5 on 2022-06-21 15:25

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_comments_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_date',
            new_name='create_date',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='created_date',
        ),
        migrations.AddField(
            model_name='comments',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 21, 15, 25, 1, 220421, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='author',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='comments',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
