# Generated by Django 3.2.5 on 2022-06-21 15:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20220621_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 21, 15, 25, 54, 364051, tzinfo=utc)),
        ),
    ]
